### ISSUE TITLE
Search is showing small, unfiltered set of results with no indication of a full search results page

### ISSUE THREAD

**Issue by tmquinn** [gabrielcsapo/docusaurus-plugin-search-local#15]
While conducting a search on `Lix` from the Cmd-K prompt in the new Voyager Web Docs, I was shown results that looked like this
![image](https://user-images.githubusercontent.com/251802/153082343-567edf18-a150-40e4-881a-a083e5ce112e.png)

The results claimed only 8 documents were found and it was returning results from non-web documentation.

In actuality there were 91 documents with these results:
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/251802/153082621-fcda7b43-6ecd-476c-b66a-49723e6caedf.png">

So the issues are:
1. We should be able to limit searches to just the web docs.
2. The search results dropdown should not indicate there are far fewer results than there actually are
3. There should be some way to go directly to the full search results

**Comment by lbdm44** [comment]
This bug has been resolved and will be released with the upcoming beta release.
