### ISSUE TITLE
Remove language support for v1

### ISSUE THREAD

**Issue by lbdm44** [gabrielcsapo/docusaurus-plugin-search-local#21]
## Overview

I propose we remove non-english language support for v1 with plans on introducing it back in a later version.

## Background

There is currently a lot of code that does not follow industry standards with regards to support various languages within this plugin. In order to progress the feature set and clean this codebase up it would be much easier to rip out language support now and add it back in once the plugin is in a good place and the need arises.

**Comment by gabrielcsapo** [comment]
agreed, this is a good move to make sure we have a stable search platform and add languages back later.
