### ISSUE TITLE
Enable searching from the middle of the word?

### ISSUE THREAD

**Issue by yudongqiu** [gabrielcsapo/docusaurus-plugin-search-local#47]
Reason: For technical terms, people may not remember the full name, but only parts. Searching parts in the middle of a long string does not show result.

Screenshots:
1. search full term or prefix works:
https://gabrielcsapo.github.io/docusaurus-plugin-search-local/search/?q=docsRouteBasePath
<img width="825" alt="Screen Shot 2022-04-19 at 2 44 09 PM" src="https://user-images.githubusercontent.com/6952367/164106926-ece7ba64-5713-4f42-a3f3-f48250b0d004.png">

2. Search part term does not show any result:
https://gabrielcsapo.github.io/docusaurus-plugin-search-local/search/?q=RouteBasePath

<img width="710" alt="Screen Shot 2022-04-19 at 2 44 47 PM" src="https://user-images.githubusercontent.com/6952367/164107045-a0684435-bfa5-4650-920f-9ec9d471b05e.png">

Just for comparison, the algolia search engine seems to support such use case:
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-pages#mdxPageComponent
<img width="608" alt="Screen Shot 2022-04-19 at 2 48 04 PM" src="https://user-images.githubusercontent.com/6952367/164107457-0c7e9fc1-f76c-4bcd-bb0f-69c0859b5dd8.png">

**Comment by Ancient-Dragon** [comment]
@gabrielcsapo / @lbdm44 Do you know if you're planning to implement this? Would be really beneficial, thanks!

**Comment by gabrielcsapo** [comment]
Looking into a fix now @Ancient-Dragon

**Comment by gabrielcsapo** [comment]
I created a PR for the fix. will update when we have a published version.
