### ISSUE TITLE
Search shows multiple results with the same title

### ISSUE THREAD

**Issue by tylerbecks** [gabrielcsapo/docusaurus-plugin-search-local#49]
When I search for `spark`, it's showing multiple results for the same page with the same header. They are not all the same link, however, here are the results:

- https://pages.linkedin.ghe.com/multiproduct/web-docs/docs/tags/assets/?_highlight=spark
- https://pages.linkedin.ghe.com/multiproduct/web-docs/docs/tags/cdn/?_highlight=spark
- https://pages.linkedin.ghe.com/multiproduct/web-docs/docs/tags/spark/?_highlight=spark
- https://pages.linkedin.ghe.com/multiproduct/web-docs/docs/tags/web/?_highlight=spark
- https://pages.linkedin.ghe.com/multiproduct/web-docs/docs/reference/spark-placeholders/?_highlight=spark

The last one is the only one I expect to show up.

<img width="1058" alt="Screen Shot 2022-08-02 at 6 01 34 PM" src="https://user-images.githubusercontent.com/16826230/182488097-dc6dd18c-3b72-4a32-bb70-7cc06a38e171.png">

**Comment by gabrielcsapo** [comment]
We should represent tag pages differently than the others. I will update this PR when I have a link to a fix.

**Comment by gabrielcsapo** [comment]
# Before

<img width="1518" alt="Screenshot 2022-10-22 at 3 07 44 PM" src="https://user-images.githubusercontent.com/1854811/197364094-b3473b49-1e66-4c32-a21a-a56e1d96cd32.png">

# After

<img width="1518" alt="Screenshot 2022-10-22 at 3 06 31 PM" src="https://user-images.githubusercontent.com/1854811/197364098-53d6a91d-76cc-46a0-b922-32cb650a55f5.png">

@tylerbecks thoughts on this update?

**Comment by gabrielcsapo** [comment]
PR with fix here https://github.com/gabrielcsapo/docusaurus-plugin-search-local/pull/58
