### ISSUE TITLE
View all search results shows an error page

### ISSUE THREAD

**Issue by hs-saunved** [gabrielcsapo/docusaurus-plugin-search-local#53]
This is visible on the demo website too.

Steps to reproduce:
1. Go to the demo website of this project
2. Type "a" or any other common character
3. Scroll down and click on "See All Results"
4. An error page shows up

E.g. this page is throwing an error: https://gabrielcsapo.github.io/docusaurus-plugin-search-local/search/?q=a

This is the error message:
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

React's hint on this page is as follows:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by gabrielcsapo** [comment]
should be fixed in the linked PR. I will update this with a version when we publish.
